<a href="https://colab.research.google.com/github/mayank444/Cancer-Prediction/blob/main/Cancer_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import sklearn

# Load Dataset

In [2]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [3]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [7]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

# Create Dataframe

In [8]:
df = pd.DataFrame(np.c_[data.data,data.target], columns=[list(data.feature_names)+['target']])

In [9]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [10]:
df.head()

mean radius mean texture  ... worst fractal dimension target
0       17.99        10.38  ...                 0.11890    0.0
1       20.57        17.77  ...                 0.08902    0.0
2       19.69        21.25  ...                 0.08758    0.0
3       11.42        20.38  ...                 0.17300    0.0
4       20.29        14.34  ...                 0.07678    0.0

[5 rows x 31 columns]

In [11]:
df.shape

(569, 31)

# Split Data

In [12]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [13]:
print('shape of X:',X.shape)
print('shape of y:',y.shape)

shape of X: (569, 30)
shape of y: (569,)


In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2020)
print('shape of X_train:',X_train.shape)
print('shape of X_test:',X_test.shape)
print('shape of y_train:',y_train.shape)
print('shape of y_test:',y_test.shape)

shape of X_train: (455, 30)
shape of X_test: (114, 30)
shape of y_train: (455,)
shape of y_test: (114,)


In [15]:
X_train.describe()

mean radius mean texture  ... worst symmetry worst fractal dimension
count  455.000000   455.000000  ...     455.000000              455.000000
mean    14.045567    19.249385  ...       0.287864                0.083339
std      3.459058     4.346806  ...       0.060145                0.016916
min      6.981000     9.710000  ...       0.156500                0.055040
25%     11.645000    16.265000  ...       0.249350                0.071365
50%     13.280000    18.750000  ...       0.281200                0.079440
75%     15.680000    21.790000  ...       0.315300                0.092055
max     28.110000    39.280000  ...       0.663800                0.173000

[8 rows x 30 columns]

# Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

In [17]:
X_train_sc = pd.DataFrame(X_train_sc,columns=data['feature_names'])
X_test_sc = pd.DataFrame(X_test_sc,columns=data['feature_names'])

In [18]:
X_train_sc.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0    -0.053706     -0.534171  ...        1.250622                 1.335183
1     0.878208      1.819568  ...        0.218640                 0.429703
2    -0.725147     -1.107636  ...       -0.914875                -0.118319
3     0.070742     -0.559505  ...       -0.700156                -1.310238
4    -0.050812     -0.699992  ...       -0.859947                -0.722564

[5 rows x 30 columns]

In [19]:
X_train_sc.describe().round(2)

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
count       455.00        455.00  ...          455.00                   455.00
mean          0.00          0.00  ...            0.00                    -0.00
std           1.00          1.00  ...            1.00                     1.00
min          -2.04         -2.20  ...           -2.19                    -1.67
25%          -0.69         -0.69  ...           -0.64                    -0.71
50%          -0.22         -0.12  ...           -0.11                    -0.23
75%           0.47          0.59  ...            0.46                     0.52
max           4.07          4.61  ...            6.26                     5.31

[8 rows x 30 columns]

# Train SVM model

In [20]:
from sklearn.linear_model import LogisticRegression
classification = LogisticRegression()
classification.fit(X_train_sc,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
classification.score(X_test_sc,y_test)

0.9736842105263158

# Predict Cancer

In [22]:
preds = classification.predict(X_test_sc)

In [23]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,preds)

In [24]:
cm

array([[47,  1],
       [ 2, 64]])

In [25]:
# values came in the report of patient
patient = [17.99,10.38,132.90,1001.0,0.11840,0.27760,0.0869,0.14710,0.1809,0.05667,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.01860,0.01340,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890]
patient_sc = sc.transform(np.array([patient]))
patient_sc

array([[ 1.14157516e+00, -2.04268291e+00,  1.74196219e+00,
         1.02590938e+00,  1.62044096e+00,  3.42348005e+00,
        -1.37598791e-03,  2.64970572e+00,  4.89224138e-02,
        -8.65733415e-01,  2.47642647e+00, -5.67294216e-01,
         2.77495792e+00,  2.44785280e+00, -2.35166965e-01,
         1.35781809e+00, -4.24208978e-01,  2.51463610e-01,
         1.19270040e+00,  9.31263139e-01,  1.94777877e+00,
        -1.35487239e+00,  2.37210178e+00,  2.06352534e+00,
         1.31020065e+00,  2.82342306e+00,  2.23450433e+00,
         2.38372721e+00,  2.86683913e+00,  2.10454451e+00]])

In [26]:
prediction = classification.predict(patient_sc)
prediction

array([0.])

In [27]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [28]:
if prediction[0]==0:
  print('Patient has cancer')
else:
  print('Patient has no cancer')

Patient has cancer
